<a href="https://colab.research.google.com/github/Imran-Github22/Programming-For-Data/blob/main/worksheet/15_1_Encoding_and_Dummy_Coding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Encoding Data  
When we encode data, we remodel a numeric column in a dataframe to be on a standard scale (0 or 1).   
For example if we had a column of BMI scores, we could encode that column so that all scores greater than or equal to 25 were recoded to the value 1 (bad) and all scores less than 25 were recoded to 0 (good).  

For example:  

` def encode_bmi(df):`       
> `if df['bmi'] >= 25:`  
> >  `return 1`   

>`else`:  
> >`return 0`  

`df["bmi"] = df.apply(encode_bmi, axis=1)`

### Challenge 1 - prepare dataset for encoding 
---
1. Read Covid vaccination data from the `by_country` sheet in the Excel file at this link : https://github.com/lilaceri/Working-with-data-/blob/342abab10d93c4bf23b5c55a50f189f12a137c5f/Data%20Sets%20for%20code%20divisio/Covid%20Vaccination%20Data.xlsx?raw=true
2. Find out which columns have missing values
3. Remove all rows with missing data in the total_vaccination column  
4. Remove all rows with missing data in the daily_vaccinations_per_million 
4. find the median daily_vaccinations_per_million, storing this in a variable for use later     


**Test output**:  
1. dataframe is saved in a variable
2. 
```
RangeIndex: 14994 entries, 0 to 14993
Data columns (total 15 columns):
    Column                               Non-Null Count  Dtype         
                                
 0   country                              14994 non-null  object        
 1   iso_code                             14994 non-null  object        
 2   date                                 14994 non-null  datetime64[ns]
 3   total_vaccinations                   9011 non-null   float64       
 4   people_vaccinated                    8370 non-null   float64       
 5   people_fully_vaccinated              6158 non-null   float64       
 6   daily_vaccinations_raw               7575 non-null   float64       
 7   daily_vaccinations                   14796 non-null  float64       
 8   total_vaccinations_per_hundred       9011 non-null   float64       
 9   people_vaccinated_per_hundred        8370 non-null   float64       
 10  people_fully_vaccinated_per_hundred  6158 non-null   float64       
 11  daily_vaccinations_per_million       14796 non-null  float64       
 12  vaccines                             14994 non-null  object        
 13  source_name                          14994 non-null  object        
 14  source_website                       14994 non-null  object        
dtypes: datetime64[ns](1), float64(9), object(5)
memory usage: 1.7+ MB
```
3. 9011 rows Ã— 15 columns  
4. 8815 rows * 15 columns 
5. 6.65

In [1]:
import pandas as pd
import numpy as np

url = "https://github.com/lilaceri/Working-with-data-/blob/342abab10d93c4bf23b5c55a50f189f12a137c5f/Data%20Sets%20for%20code%20divisio/Covid%20Vaccination%20Data.xlsx?raw=true"

# Task 1 
def create_dataframe(url, db_type='csv', sheetname=None):
  import pandas as pd
  if db_type == 'csv':
    df = pd.read_csv(url)
  elif db_type == 'excel':
    if sheetname == None:
      df = pd.read_excel(url)
    else:
      df = pd.read_excel(url, sheet_name=sheetname)
  else:
    df = pd.read_csv(url)
  return df

covid_df = create_dataframe(url, db_type='excel', sheetname='by_country')

In [2]:
# Task 2
display(covid_df.info())
display(covid_df.head())

# Task 3
covid_total_df = covid_df.dropna(subset=['total_vaccinations'])
print('')
display(covid_total_df.info())

# Task 4
covid_daily_df = covid_total_df.dropna(subset=['daily_vaccinations_per_million'])
print('')
display(covid_daily_df.info())

# Task 5
np_daily_vac_miln = np.array(covid_daily_df['daily_vaccinations_per_million'], np.float64)
daily_vac_miln_median = np.median(np_daily_vac_miln)

print(f'\nMedian (daily_vaccinations_per_million): {daily_vac_miln_median}')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14994 entries, 0 to 14993
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              14994 non-null  object
 1   iso_code                             14994 non-null  object
 2   date                                 14994 non-null  datetime64[ns]
 3   total_vaccinations                   9011 non-null   float64
 4   people_vaccinated                    8370 non-null   float64
 5   people_fully_vaccinated              6158 non-null   float64
 6   daily_vaccinations_raw               7575 non-null   float64
 7   daily_vaccinations                   14796 non-null  float64
 8   total_vaccinations_per_hundred       9011 non-null   float64
 9   people_vaccinated_per_hundred        8370 non-null   float64
 10  people_fully_vaccinated_per_hundred  6158 non-null   float64
 11  daily_vaccinations_per_million       14796 non-null  float64
 12  vaccines                             14994 non-null  object
 13  source_name                          14994 non-null  object
 14  source_website                       14994 non-null  object
dtypes: datetime64[ns](1), float64(9), object(5)
memory usage: 1.7+ MB

None

       country  ...                                     source_website
0  Afghanistan  ...  https://reliefweb.int/report/afghanistan/afgha...
1  Afghanistan  ...  https://reliefweb.int/report/afghanistan/afgha...
2  Afghanistan  ...  https://reliefweb.int/report/afghanistan/afgha...
3  Afghanistan  ...  https://reliefweb.int/report/afghanistan/afgha...
4  Afghanistan  ...  https://reliefweb.int/report/afghanistan/afgha...

[5 rows x 15 columns]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9011 entries, 0 to 14993
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              9011 non-null   object
 1   iso_code                             9011 non-null   object
 2   date                                 9011 non-null   datetime64[ns]
 3   total_vaccinations                   9011 non-null   float64
 4   people_vaccinated                    8294 non-null   float64
 5   people_fully_vaccinated              6157 non-null   float64
 6   daily_vaccinations_raw               7575 non-null   float64
 7   daily_vaccinations                   8816 non-null   float64
 8   total_vaccinations_per_hundred       9011 non-null   float64
 9   people_vaccinated_per_hundred        8294 non-null   float64
 10  people_fully_vaccinated_per_hundred  6157 non-null   float64
 11  daily_vaccinations_per_million       8816 non-null   float64
 12  vaccines                             9011 non-null   object
 13  source_name                          9011 non-null   object
 14  source_website                       9011 non-null   object
dtypes: datetime64[ns](1), float64(9), object(5)
memory usage: 1.1+ MB

None

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8816 entries, 6 to 14993
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              8816 non-null   object
 1   iso_code                             8816 non-null   object
 2   date                                 8816 non-null   datetime64[ns]
 3   total_vaccinations                   8816 non-null   float64
 4   people_vaccinated                    8126 non-null   float64
 5   people_fully_vaccinated              6143 non-null   float64
 6   daily_vaccinations_raw               7575 non-null   float64
 7   daily_vaccinations                   8816 non-null   float64
 8   total_vaccinations_per_hundred       8816 non-null   float64
 9   people_vaccinated_per_hundred        8126 non-null   float64
 10  people_fully_vaccinated_per_hundred  6143 non-null   float64
 11  daily_vaccinations_per_million       8816 non-null   float64
 12  vaccines                             8816 non-null   object
 13  source_name                          8816 non-null   object
 14  source_website                       8816 non-null   object
dtypes: datetime64[ns](1), float64(9), object(5)
memory usage: 1.1+ MB

None

Median (daily_vaccinations_per_million): 1915.5

### Challenge 2 - encode daily vaccinations 
---

Write a function to encode daily vaccinations per million, where values greater than or equal to median = 1 and values less than median = 0 

**Test output**: 

using describe()
```
count    8816.000000
mean        0.991493
std         0.091847
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         1.000000
Name: daily_vaccinations_per_million, dtype: float64
```

In [3]:
# Task
def encode_daily(df, **kwds):
  key = kwds['key']
  median = kwds['median']
  if df[key] >= median:
    return 1
  else:
    return 0
  return

key = 'daily_vaccinations_per_million'
covid_daily_df['daily_vac_encoded'] = covid_daily_df.apply(encode_daily, axis=1, key=key, median=daily_vac_miln_median)
display(covid_daily_df['daily_vac_encoded'].describe())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

count    8816.000000
mean        0.500000
std         0.500028
min         0.000000
25%         0.000000
50%         0.500000
75%         1.000000
max         1.000000
Name: daily_vac_encoded, dtype: float64

### Challenge 3 - Encoding total vaccinations   
---
The United Kingdom has been praised for its fast vaccine rollout. 
1. Find the minimum total vaccinations for the United Kingdom 
2. Write a function to encode total_vaccinations column so that all values less than the UK's min are 0 and all values greater than or equal to the UK's min are coded as 1 
3. Display the unique countries for which total vaccinated is at the same rate or more than the UK

**Test output**:

1. 1402432.0
2. `df['total_vaccinations'].describe()` should output:
```
count    9011.00000
mean        0.29808
std         0.45744
min         0.00000
25%         0.00000
50%         0.00000
75%         1.00000
max         1.00000
Name: total_vaccinations, dtype: float64
```
3. 
```
array(['Argentina', 'Australia', 'Austria', 'Azerbaijan', 'Bangladesh',
       'Belgium', 'Brazil', 'Cambodia', 'Canada', 'Chile', 'China',
       'Colombia', 'Czechia', 'Denmark', 'Dominican Republic', 'England',
       'Finland', 'France', 'Germany', 'Greece', 'Hong Kong', 'Hungary',
       'India', 'Indonesia', 'Ireland', 'Israel', 'Italy', 'Japan',
       'Kazakhstan', 'Malaysia', 'Mexico', 'Morocco', 'Nepal',
       'Netherlands', 'Norway', 'Pakistan', 'Peru', 'Philippines',
       'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Saudi Arabia',
       'Scotland', 'Serbia', 'Singapore', 'Slovakia', 'South Korea',
       'Spain', 'Sweden', 'Switzerland', 'Thailand', 'Turkey',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Wales'], dtype=object)
```

In [4]:
# Task 1
country_min = covid_total_df.groupby(['country'])['total_vaccinations'].min()
uk_min = country_min['United Kingdom']
display(uk_min)

# Task 2
def encode_total(df, **kwds):
  key = kwds['key']
  min = kwds['min']
  if df[key] >= min:
    return 1
  else:
    return 0
  return

key = 'total_vaccinations'
covid_total_df['total_vac_encoded'] = covid_total_df.apply(encode_total, axis=1, key=key, min=uk_min)
display(covid_total_df['total_vac_encoded'].describe())

# Task 3
covid_total_df_enc = covid_total_df[covid_total_df['total_vac_encoded'] == 1]['country'].unique()
print('')
display(covid_total_df_enc)

1402432.0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

count    9011.00000
mean        0.29808
std         0.45744
min         0.00000
25%         0.00000
50%         0.00000
75%         1.00000
max         1.00000
Name: total_vac_encoded, dtype: float64

array(['Argentina', 'Australia', 'Austria', 'Azerbaijan', 'Bangladesh',
       'Belgium', 'Brazil', 'Cambodia', 'Canada', 'Chile', 'China',
       'Colombia', 'Czechia', 'Denmark', 'Dominican Republic', 'England',
       'Finland', 'France', 'Germany', 'Greece', 'Hong Kong', 'Hungary',
       'India', 'Indonesia', 'Ireland', 'Israel', 'Italy', 'Japan',
       'Kazakhstan', 'Malaysia', 'Mexico', 'Morocco', 'Nepal',
       'Netherlands', 'Norway', 'Pakistan', 'Peru', 'Philippines',
       'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Saudi Arabia',
       'Scotland', 'Serbia', 'Singapore', 'Slovakia', 'South Korea',
       'Spain', 'Sweden', 'Switzerland', 'Thailand', 'Turkey',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Wales'], dtype=object)

### Challenge 4 - create new series of total vaccinations for each manufacturer
---

To create a new column in your dataframe:

`df['new_column'] = ...`

For example:

* to duplicate an existing column
  * `df['new_column'] = df['old_column']`
* to add two columns together 
  * `df['new_column'] = df['column1'] + df['column2']`
* to make a percentages column 
  * `df['new_column'] = (df['column1']/df['column1].sum()) * 100`

  
1. read data from 'by_manufacturer' sheet from Covid data 
2. find the sum of total vaccinations for each manufacturer
3. create a new column that has the total vaccinations as a percentage of the overall sum of total vaccinations 
4. find the median percentage 
5. create a new column called 'encoded_percentages' which duplicates the percentages column
6. encode the encoded_percentages column so that any values greater than or equal to the median percentage = 1 and any lesser than = 0 


**Test output**:

1.
2. 
```
vaccine
Johnson&Johnson        264839828
Moderna               5548036383
Oxford/AstraZeneca     539433203
Pfizer/BioNTech       8690461304
Sinovac                604660293
Name: total_vaccinations, dtype: int64
```
3. 
```
	location	date	vaccine	total_vaccinations	percentages
0	Chile	2020-12-24	Pfizer/BioNTech	420	0.000003
1	Chile	2020-12-25	Pfizer/BioNTech	5198	0.000033
2	Chile	2020-12-26	Pfizer/BioNTech	8338	0.000053
3	Chile	2020-12-27	Pfizer/BioNTech	8649	0.000055
4	Chile	2020-12-28	Pfizer/BioNTech	8649	0.000055
...	...	...	...	...	...
3291	United States	2021-05-01	Moderna	105947940	0.677095
3292	United States	2021-05-01	Pfizer/BioNTech	129013657	0.824504
3293	United States	2021-05-02	Johnson&Johnson	8374395	0.053519
3294	United States	2021-05-02	Moderna	106780082	0.682413
3295	United States	2021-05-02	Pfizer/BioNTech	130252779	0.832423
3296 rows Ã— 5 columns
```
4. 0.0011110194374896931
5. 
```
location	date	vaccine	total_vaccinations	percentage_of_total	encoded_percentages
0	Chile	2020-12-24	Pfizer/BioNTech	420	0.000003	0.000003
1	Chile	2020-12-25	Pfizer/BioNTech	5198	0.000033	0.000033
2	Chile	2020-12-26	Pfizer/BioNTech	8338	0.000053	0.000053
3	Chile	2020-12-27	Pfizer/BioNTech	8649	0.000055	0.000055
4	Chile	2020-12-28	Pfizer/BioNTech	8649	0.000055	0.000055
...	...	...	...	...	...	...
3291	United States	2021-05-01	Moderna	105947940	0.677095	0.677095
3292	United States	2021-05-01	Pfizer/BioNTech	129013657	0.824504	0.824504
3293	United States	2021-05-02	Johnson&Johnson	8374395	0.053519	0.053519
3294	United States	2021-05-02	Moderna	106780082	0.682413	0.682413
3295	United States	2021-05-02	Pfizer/BioNTech	130252779	0.832423	0.832423
3296 rows Ã— 6 columns
```
6. 
```
	location	date	vaccine	total_vaccinations	percentages	encode	encoded
0	Chile	2020-12-24	Pfizer/BioNTech	420	0.000003	0.000003	0
1	Chile	2020-12-25	Pfizer/BioNTech	5198	0.000033	0.000033	0
2	Chile	2020-12-26	Pfizer/BioNTech	8338	0.000053	0.000053	0
3	Chile	2020-12-27	Pfizer/BioNTech	8649	0.000055	0.000055	0
4	Chile	2020-12-28	Pfizer/BioNTech	8649	0.000055	0.000055	0
...	...	...	...	...	...	...	...
3291	United States	2021-05-01	Moderna	105947940	0.677095	0.677095	1
3292	United States	2021-05-01	Pfizer/BioNTech	129013657	0.824504	0.824504	1
3293	United States	2021-05-02	Johnson&Johnson	8374395	0.053519	0.053519	1
3294	United States	2021-05-02	Moderna	106780082	0.682413	0.682413	1
3295	United States	2021-05-02	Pfizer/BioNTech	130252779	0.832423	0.832423	1
3296 rows Ã— 7 columns
```

In [5]:
# Task 1
covid_manu_df = create_dataframe(url, db_type='excel', sheetname='by_manufacturer')
display(covid_manu_df.info())
display(covid_manu_df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3296 entries, 0 to 3295
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   location            3296 non-null   object
 1   date                3296 non-null   datetime64[ns]
 2   vaccine             3296 non-null   object
 3   total_vaccinations  3296 non-null   int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 103.1+ KB

None

  location       date          vaccine  total_vaccinations
0    Chile 2020-12-24  Pfizer/BioNTech                 420
1    Chile 2020-12-25  Pfizer/BioNTech                5198
2    Chile 2020-12-26  Pfizer/BioNTech                8338
3    Chile 2020-12-27  Pfizer/BioNTech                8649
4    Chile 2020-12-28  Pfizer/BioNTech                8649

In [6]:
# Task 2
covid_manu_sum_df = covid_manu_df.groupby(['vaccine'])['total_vaccinations'].sum()
display(covid_manu_sum_df)

vaccine
Johnson&Johnson        264839828
Moderna               5548036383
Oxford/AstraZeneca     539433203
Pfizer/BioNTech       8690461304
Sinovac                604660293
Name: total_vaccinations, dtype: int64

In [7]:
# Task 3
covid_manu_df['percentages'] = (covid_manu_df['total_vaccinations']/covid_manu_sum_df.sum()) * 100
display(covid_manu_df.head())
print('')
display(covid_manu_df.tail())

  location       date          vaccine  total_vaccinations  percentages
0    Chile 2020-12-24  Pfizer/BioNTech                 420     0.000003
1    Chile 2020-12-25  Pfizer/BioNTech                5198     0.000033
2    Chile 2020-12-26  Pfizer/BioNTech                8338     0.000053
3    Chile 2020-12-27  Pfizer/BioNTech                8649     0.000055
4    Chile 2020-12-28  Pfizer/BioNTech                8649     0.000055

           location       date  ... total_vaccinations  percentages
3291  United States 2021-05-01  ...          105947940     0.677095
3292  United States 2021-05-01  ...          129013657     0.824504
3293  United States 2021-05-02  ...            8374395     0.053519
3294  United States 2021-05-02  ...          106780082     0.682413
3295  United States 2021-05-02  ...          130252779     0.832423

[5 rows x 5 columns]

In [8]:
# Task 4
percentage_median = np.median(covid_manu_df['percentages'])
print(f'Percentages Median: {percentage_median}')

Percentages Median: 0.0011110194374896931

In [9]:
# Task 5
covid_manu_df['encode'] = covid_manu_df['percentages']

In [10]:
# Task 6
def encode_percentages(df, **kwds):
  key = kwds['key']
  median = kwds['median']
  if df[key] >= median:
    return 1
  else:
    return 0
  return

key = 'encode'
covid_manu_df['encoded'] = covid_manu_df.apply(encode_percentages, axis=1, key=key, median=percentage_median)
display(covid_manu_df['encoded'].describe())
display(covid_manu_df.head())
display(covid_manu_df.tail())

count    3296.000000
mean        0.500000
std         0.500076
min         0.000000
25%         0.000000
50%         0.500000
75%         1.000000
max         1.000000
Name: encoded, dtype: float64

  location       date          vaccine  ...  percentages    encode  encoded
0    Chile 2020-12-24  Pfizer/BioNTech  ...     0.000003  0.000003        0
1    Chile 2020-12-25  Pfizer/BioNTech  ...     0.000033  0.000033        0
2    Chile 2020-12-26  Pfizer/BioNTech  ...     0.000053  0.000053        0
3    Chile 2020-12-27  Pfizer/BioNTech  ...     0.000055  0.000055        0
4    Chile 2020-12-28  Pfizer/BioNTech  ...     0.000055  0.000055        0

[5 rows x 7 columns]

           location       date          vaccine  ...  percentages    encode  encoded
3291  United States 2021-05-01          Moderna  ...     0.677095  0.677095        1
3292  United States 2021-05-01  Pfizer/BioNTech  ...     0.824504  0.824504        1
3293  United States 2021-05-02  Johnson&Johnson  ...     0.053519  0.053519        1
3294  United States 2021-05-02          Moderna  ...     0.682413  0.682413        1
3295  United States 2021-05-02  Pfizer/BioNTech  ...     0.832423  0.832423        1

[5 rows x 7 columns]

### Exercise 8 - encode daily vaccinations 

1. find the median daily vaccinations per 1 million 
2. write a function to encode daily vaccinations per 1 million, where values greater than or equal to median = 1 and values less than median = 0 

Output: 

1. 1915.5
2. 
```
0        0
6        0
22       0
44       0
59       0
        ..
14989    0
14990    0
14991    0
14992    0
14993    0
Name: daily_vaccinations_per_million, Length: 9011, dtype: int64
```

### Exercise 9 - Encoding vaccinations per hundred  
---
The United Kingdom has been praised for its fast vaccine rollout. 
1. find the minimum total vaccinations for the United Kingdom 
2. save this value in a variable rounded down to an integer
3. write a function to encode total_vaccinations column so that all values less than the UK's min are 0 and all values greater than or equal to the UK's min are coded as 1 
4. display the countries which total vaccinated is at the same rate or more than the UK

Output:

1. 1402432.0
2. 1402432
3. `df['people_vaccinated_per_hundred']` should output:
```
0        0
6        0
22       0
44       0
59       0
        ..
14989    0
14990    0
14991    0
14992    0
14993    0
Name: total_vaccinations, Length: 9011, dtype: int64
```
4. 
```
array(['Argentina', 'Australia', 'Austria', 'Azerbaijan', 'Bangladesh',
       'Belgium', 'Brazil', 'Cambodia', 'Canada', 'Chile', 'China',
       'Colombia', 'Czechia', 'Denmark', 'Dominican Republic', 'England',
       'Finland', 'France', 'Germany', 'Greece', 'Hong Kong', 'Hungary',
       'India', 'Indonesia', 'Ireland', 'Israel', 'Italy', 'Japan',
       'Kazakhstan', 'Malaysia', 'Mexico', 'Morocco', 'Nepal',
       'Netherlands', 'Norway', 'Pakistan', 'Peru', 'Philippines',
       'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Saudi Arabia',
       'Scotland', 'Serbia', 'Singapore', 'Slovakia', 'South Korea',
       'Spain', 'Sweden', 'Switzerland', 'Thailand', 'Turkey',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Wales'], dtype=object)
```

### Exercise 10 - create new series of total vaccinations percentages
---

To create a new column in your dataframe:

`df['new_column'] = ...`

For example:

* to duplicate an existing column
  * `df['new_column'] = df['old_column']`
* to add two columns together 
  * `df['new_column'] = df['column1'] + df['column2']`
* to make a percentages column 
  * `df['new_column'] = (df['column1']/df['column1].sum()) * 100`  
  


1. read data from 'by_manufacturer' sheet from Covid data 
2. find the sum of total vaccinations for each manufacturer
3. create a new column that has the total vaccinations as a percentage of the overall sum of total vaccinations 
4. find the median percentage 
5. create a new column called 'encoded_percentages' which duplicates the percentages column
6. encode the encoded_percentages column so that any values greater than or equal to the median percentage = 1 and any lesser than = 0 


Output:

1.
2. 
```
vaccine
Johnson&Johnson        264839828
Moderna               5548036383
Oxford/AstraZeneca     539433203
Pfizer/BioNTech       8690461304
Sinovac                604660293
Name: total_vaccinations, dtype: int64
```
3. 
```
	location	date	vaccine	total_vaccinations	percentages
0	Chile	2020-12-24	Pfizer/BioNTech	420	0.000003
1	Chile	2020-12-25	Pfizer/BioNTech	5198	0.000033
2	Chile	2020-12-26	Pfizer/BioNTech	8338	0.000053
3	Chile	2020-12-27	Pfizer/BioNTech	8649	0.000055
4	Chile	2020-12-28	Pfizer/BioNTech	8649	0.000055
...	...	...	...	...	...
3291	United States	2021-05-01	Moderna	105947940	0.677095
3292	United States	2021-05-01	Pfizer/BioNTech	129013657	0.824504
3293	United States	2021-05-02	Johnson&Johnson	8374395	0.053519
3294	United States	2021-05-02	Moderna	106780082	0.682413
3295	United States	2021-05-02	Pfizer/BioNTech	130252779	0.832423
3296 rows Ã— 5 columns
```
4. 0.0011110194374896931
5. 
6. 
```
	location	date	vaccine	total_vaccinations	percentages	encode	encoded
0	Chile	2020-12-24	Pfizer/BioNTech	420	0.000003	0.000003	0
1	Chile	2020-12-25	Pfizer/BioNTech	5198	0.000033	0.000033	0
2	Chile	2020-12-26	Pfizer/BioNTech	8338	0.000053	0.000053	0
3	Chile	2020-12-27	Pfizer/BioNTech	8649	0.000055	0.000055	0
4	Chile	2020-12-28	Pfizer/BioNTech	8649	0.000055	0.000055	0
...	...	...	...	...	...	...	...
3291	United States	2021-05-01	Moderna	105947940	0.677095	0.677095	1
3292	United States	2021-05-01	Pfizer/BioNTech	129013657	0.824504	0.824504	1
3293	United States	2021-05-02	Johnson&Johnson	8374395	0.053519	0.053519	1
3294	United States	2021-05-02	Moderna	106780082	0.682413	0.682413	1
3295	United States	2021-05-02	Pfizer/BioNTech	130252779	0.832423	0.832423	1
3296 rows Ã— 7 columns
```

# Reflection
----

## What skills have you demonstrated in completing this notebook?

Your answer:

## What caused you the most difficulty?

Your answer: